name: Test Callable File Patterns
on:
  push:
    branches:
      - drstrangelove/github-actions

jobs:
  checkfiles:
    uses: looker-open-source/sdk-codegen/.github/workflows/check-files.yml@drstrangelove/github-actions

  work:
    runs-on: ubuntu-latest
    needs: checkfiles
    # if: needs.checkfiles.outputs.codegen
    steps:
      - name: Outputs
        run: |
          echo "${{ needs.checkfiles.outputs.filters }}"
          echo "apix: ${{ needs.checkfiles.outputs.apix }}"
          echo "codegen: ${{ needs.checkfiles.outputs.codegen }}"
          echo "hackathon: ${{ needs.checkfiles.outputs.hackathon }}"
          echo "python: ${{ needs.checkfiles.outputs.python }}"
          echo "resources: ${{ needs.checkfiles.outputs.resources }}"
          echo "tssdk: ${{ needs.checkfiles.outputs.tssdk }}"
          echo "Check value access from filters JSON"
          echo "apix: ${{ fromJSON(needs.checkfiles.outputs.filters).apix }}"
          echo "codegen: ${{ fromJSON(needs.checkfiles.outputs.filters).codegen }}"
          echo "hackathon: ${{ fromJSON(needs.checkfiles.outputs.filters).hackathon }}"
          echo "python: ${{ fromJSON(needs.checkfiles.outputs.filters).python }}"
          echo "resources: ${{ fromJSON(needs.checkfiles.outputs.filters).resources }}"
          echo "tssdk: ${{ fromJSON(needs.checkfiles.outputs.filters).tssdk }}"
      - name: Check
        if: needs.checkfiles.outputs.apix == 'true'
        run: |
          echo "apix: ${{ needs.checkfiles.outputs.apix }}"

  work2:
    runs-on: ubuntu-latest
    needs: checkfiles
    if: needs.checkfiles.outputs.codegen == 'true'
    steps:
      - name: Outputs
        run: |
          echo "Codegen is true"
