name: Reusable File Patterns
on:
  workflow_call:

jobs:
  checkfiles:
    runs-on: ubuntu-latest
    outputs:
      filters: ${{ toJSON(steps.filter.outputs) }}
      apix: ${{ steps.filter.outputs.apix }}
      codegen: ${{ steps.filter.outputs.codegen }}
      hackathon: ${{ steps.filter.outputs.hackathon }}
      python: ${{ steps.filter.outputs.python }}
      resources: ${{ steps.filter.outputs.resources }}
      tssdk: ${{ steps.filter.outputs.tssdk }}

    steps:
      - name: Repo Checkout
        uses: actions/checkout@v2

      - uses: tony84727/changed-file-filter@v0.2.0
        id: filter
        with:
        # head: optional head commit SHA, default to ${{ github.event.pull_request.head.sha || github.sha }}
        # base: optional base commit SHA, default to ${{ github.event.pull_request.base.sha }}
        # or HEAD^ if not triggered by pull_request

        # filter rules in YAML format
        # <rule-name>:
        #  - <glob expression>
          filters: |
            apix:
              - packages/code-editor/**
              - packages/run-it/**
              - packages/api-explorer/**
              - packages/extension-api-explorer/**
              - packages/extension-utils/**
            codegen:
              - packages/sdk-codegen/**
              - packages/sdk-codegen-utils/**
              - packages/sdk-codegen-scripts/**
            hackathon:
              - packages/wholly-sheet/**
              - packages/hackathon/**
            python:
              - python/**
            resources:
              - bin/looker-resources-index/**
              - docs/resources/**
            tssdk:
              - packages/sdk/**
              - packages/sdk-rtl/**
              - packages/sdk-node/**
              - packages/extension-sdk/**
              - packages/extension-sdk-react/**
              - packages/extension-utils/**
      - run: |
          echo "${{ toJSON(steps.filter.outputs) }}"
          echo "apix: ${{ steps.filter.outputs.apix }}"
          echo "codegen: ${{ steps.filter.outputs.codegen }}"
          echo "hackathon: ${{ steps.filter.outputs.hackathon }}"
          echo "python: ${{ steps.filter.outputs.python }}"
          echo "resources: ${{ steps.filter.outputs.resources }}"
          echo "tssdk: ${{ steps.filter.outputs.tssdk }}"
